config/routes.rb
Rails.application.routes.draw do
  # Public routes
  root "home#index"

  get "account_registrations/new"
  get "account_registrations/create"
  get "dashboard/show", as: :dashboard
  get "home/index", as: :home

  # Auth routes
  resource :account_registrations, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :passwords, only: [:new, :create, :update], param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  validates :email_address,
    presence: true,
    uniqueness: true,
    format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :password,
    presence: true,
    length: {minimum: 8}

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/account_registrations_controller.rb
class AccountRegistrationsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]
  before_action :resume_session, only: [ :new ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      start_new_session_for @user
      redirect_to after_authentication_url,
        notice: "Account creation successful. Welcome to HostariDeploy, #{tag.u(@user.email_address)}!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private

  def authenticated?
    resume_session
  end

  def require_authentication
    resume_session || request_authentication
  end

  def resume_session
    Current.session ||= find_session_by_cookie
  end

  def find_session_by_cookie
    Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
  end

  def request_authentication
    session[:return_to_after_authenticating] = request.url
    flash[:alert] = "You must be logged in to access this page!"
    redirect_to new_session_path
  end

  def after_authentication_url
    session.delete(:return_to_after_authenticating) || dashboard_url
  end

  def start_new_session_for(user)
    user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
      Current.session = session
      cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
    end
  end

  def terminate_session
    Current.session.destroy
    cookies.delete(:session_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_authentication
  before_action :set_current_user

  def show
  end

  private

  def set_current_user
    current_session = Session.find_by(id: cookies.signed[:session_id])
    @current_user = current_session.user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  allow_unauthenticated_access(only: :index)

  def index
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      flash[:notice] = "Successfully logged in."
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    flash[:notice] = "You have successfully been signed out."
    redirect_to root_url
  end
end

app/helpers/account_registrations_helper.rb
module AccountRegistrationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/account_registrations/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Create a surveytrack account</h1>
  <%= form_with model: @user, url: account_registrations_path,
    class: "flex flex-col mt-4" do |form| %>
    <%# fields %>
    <%= form.email_field :email_address,
      required: true,
      autofocus: true,
      placeholder: "Enter your email address",
      class: "shadow border-b text-stone-300 border-stone-600 outline-none px-3 py-2 mt-2 w-full"
    %>
    <%= form.password_field :password,
      required: true,
      placeholder: "Create a password",
      class: "shadow border-b text-stone-300 border-stone-600 outline-none px-3 py-2 mt-2 w-full"
    %>
    <%= form.password_field :password_confirmation,
      required: true,
      placeholder: "Confirm your password",
      class: "shadow border-b text-stone-300 border-stone-600 outline-none px-3 py-2 mt-2 w-full mb-2"
    %>
    <% if @user.errors.any? %>
      <div class="bg-red text-red-500 px-3 py-2 rounded-lg">
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="flex flex-row gap-x-2 items-center mt-4">
      <%= form.submit "Create account",
        class: "px-2 py-2 text-white text-center bg-blue-500 hover:bg-blue-800 transition"
      %>
      <%= link_to "Already have an account? Sign in", new_session_path, 
        class: "text-white underline hover:no-underline" 
      %>
    </div>
  <% end %>
</div>

app/views/dashboard/_flash.html.erb
<% if alert = flash[:alert] %>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
<% end %>
<% if notice = flash[:notice] %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

app/views/dashboard/show.html.erb
<div class="w-full">
  <div class="flex flex-row justify-between">
    <h1 class="font-bold text-4xl">Welcome to surveytrack</h1>
    <%= button_to "Logout", session_path, method: :delete, 
      class: "px-2 py-2 text-white text-center bg-red-500 cursor-pointer hover:bg-red-800 transition"%>
  </div>
  <%= render partial: "flash" %>
  <p>Hey there, <%= @current_user.email_address %>!</p>
</div>

app/views/home/_flash.html.erb
<% if alert = flash[:alert] %>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
<% end %>
<% if notice = flash[:notice] %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

app/views/home/index.html.erb
<div class="flex flex-col">
  <%= render partial: "flash" %>
  <h1 class="font-bold text-4xl">surveytrack</h1>
  <p>a multi-survey management tool</p>
  <div class="flex flex-row gap-x-2 my-5">
    <%= link_to "login to surveytrack", new_session_path, 
    class: "px-2 py-2 text-white text-center bg-blue-500 hover:bg-blue-800 transition" %>
    <%= link_to "create account", new_account_registrations_path, 
    class: "px-2 py-2 text-white text-center bg-zinc-700 hover:bg-zinc-900 transition" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Surveytrack" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-slate-900 text-white">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>